### ISSUE TITLE
FreeBSD build problem

### ISSUE THREAD

**Issue by Peter2121** [Obsidian-StudiosInc/ecrire#1]
I have a problem building ecrire on FreeBSD. I have no strong skills in cmake build system, so I added -lintl at the end of ecrire/build/src/bin/CMakeFiles/ecrire.dir/link.txt file to build it successfully. Probably, your cmake files need some correction.
Initial error was:
`[100%] Linking C executable ecrire
/usr/bin/ld: undefined reference to symbol 'libintl_bindtextdomain' (try adding -lintl)
/usr/local/lib/libintl.so.8: could not read symbols: Bad value
cc: error: linker command failed with exit code 1 (use -v to see invocation)
*** Error code 1
`

**Comment by wltjr** [comment]
Thanks for the report. I do not have access to a FreeBSD system. I will see about creating a VM to test out or checking with someone to confirm. Not sure if that is something all should have, harmful, beneficial, etc. Or if it is something specific to FreeBSD/BSD's. I will see it is addressed either way. Thanks for the report. Also will be doing a new release shortly. I broke things like find/replace when I switched to elm code from elm entry. Those are mostly fixed just some minor bugs to address before release later today or so. I will try to get this addressed for the next release. Thanks again for the report!

**Comment by wltjr** [comment]
If you can see if this patch works. Commit 13a741653b799299b0f3fdfc1c538236380c1329. If you are unable to I will test in a VM ASAP.  You may need to cleanup and regenerate cmake files.

```
rm -fr CMakeCache.txt  CMakeFiles/ src/bin/CMakeFiles/ CPack* cmake_install.cmake src/bin/cmake_install.cmake Makefile src/bin/Makefile
cmake .
```

**Comment by Peter2121** [comment]
I've just tested on a fresh VM with a fresh git clone - it still does not work correctly. I think that the issue is not too difficult to fix, you need just change cmake files to add -lintl to link.txt in case of FreeBSD build.
Note that even correctly compiled, ecrire does not work correctly with git version of EFL - there are many issues with settings dialog.

**Comment by wltjr** [comment]
Did you check out from the new branch I created with that patch? That file you editted is auto generated by cmake. That is not the proper place to fix this issue. It should be in the main CMakeLists.txt file. The one I modified per the above patch. That should be the correct solution. It will add -lintl on FreeBSD. That is not a valid library on Linux. It is not required on Linux. Thus the conditional to set such for FreeBSD only.

You want to clone and build from this branch with the fix in place. Or you can apply the patch directly.
https://github.com/Obsidian-StudiosInc/ecrire/tree/freebsd-libintl

I am pretty sure that will fix the issue. I ran into the exact same over eo, libeo.so, -leo. Thus I know what the fix is. I am just not familiar with the cmake OS conditionals, and no access to a FreeBSD system at the moment to test. If it did not fix the issue. Then the conditional check is wrong, and not adding -lintl.

**Comment by wltjr** [comment]
What issues are you having with the settings dialog?

I did break some things when I switched to elm code. Word wrap is broken, since elm code I believe lacks that, but its should be added soon. The alpha setting  works for everything but the elm code. I am still trying to figure out what to apply the alpha to for it to be transparent. I haven't tried the font stuff that was existing, so maybe issues there. But that should work. May have to close ecrire and re-open for the font. I need to test that out. The line numbers setting should work for sure. The rest I may need to fix/tweak. Except word wrap, that I am waiting on elm code to support then it will work again as well.

**Comment by Peter2121** [comment]
Shortly, it is impossible to change the default font - any modification is not applied.

**Comment by wltjr** [comment]
Try saving, hit apply and exit ecrire and then re-launch. I may not be applying the new font when the setting is changed. In fact I pretty much know I am not. I will fix that now. It should save the correct font and size and use on next start. Unless that using font loaded from settings is messed up as well.

**Comment by wltjr** [comment]
I just tested that out and it did not work either. I will see what is wrong with font settings code. Thank you for mentioning that. Custom font is low on my interest list, so not sure when I would have tested that. That is mostly existing code, so likely not complete. Or I broke it switching to elm code.

**Comment by Peter2121** [comment]
No, the settings are neither saved nor applied.

**Comment by wltjr** [comment]
Yeah 2 issues, it does not apply when changed via settings dialog. Nor does it load them if it saved them correctly. I will make sure to resolve. Thank you for testing that and the report!

**Comment by wltjr** [comment]
I just pushed an update that fixes the font settings issue. But be forewarned you cannot go back. I have to work on coding going back to default font. For now you have to nuke the config file ~/.config/ecrire.cfg. But it will save what ever font is selected, same with size and change to that font when selected and on start.

Fixed a few more things, but a couple known issues still to address then I will do another tag/release. But git head should fix most issues including the initial issue reported. I already committed that to my branch just made the other till I was ready to push out other updates.

**Comment by wltjr** [comment]
Pretty sure this was resolved long ago. If it still exists please re-open. Thanks!
