### ISSUE TITLE
Cannot save new file

### ISSUE THREAD

**Issue by Peter2121** [Obsidian-StudiosInc/ecrire#13]
When I open ecrire, type something and try to save my work - I get a corrupted dialog (see image).
Efl version is 1.20.99, OS is FreeBSD 11.

![err-ecrire-save](https://user-images.githubusercontent.com/3807655/31176991-f24c1eb0-a914-11e7-8d0e-2580e8c3d7e9.jpg)

**Comment by wltjr** [comment]
Nice likely something changed in EFL. I will see if I can replicate. Could be something in ecrire code, but that dialog is just an elm_win_inwin with elm_fileselector. Pretty [minimal code](https://github.com/Obsidian-StudiosInc/ecrire/blob/master/src/bin/ui/file_related.c#L23). Maybe it needs a minimum size or something, but usually windows re-size to their contents. I will take a look, thanks for the report!

**Comment by wltjr** [comment]
Forgot to mention, can you check Elementary Tests, if you have them installed. The FileSelector Button or Entry. Curious if they have size issues as well.

**Comment by Peter2121** [comment]
No problems in Elementary Tests.
Voila the errors in terminal when I reproduce the problem:
```

ERR<95219>:elementary lib/elementary/efl_ui_focus_manager_calc.c:1119 _logical_movement() Warning cycle detected

ERR<95219>:elementary lib/elementary/efl_ui_layout.c:1012 _efl_ui_layout_content_set() could not swallow 0x8000001faf1fef91 into part '(null)'
ERR<95219>:elementary lib/elementary/efl_ui_focus_manager_calc.c:153 node_get() Focusable 0x8000001faf1fef91 (Elm.Fileselector) not registered in manager 0x80000000ff1febbb

```

**Comment by wltjr** [comment]
Could be bad code in ecrire, but that seems like issues resulting from a change in EFL. I will file a bug in phab. Maybe they can point out the issue in ecrire code, or what ever is causing that in EFL. Strange it did not do that for me when I switched to snapshot from earlier today. But I did have other issues with themeing. I opened an [issue](https://phab.enlightenment.org/T6143) on that. I have seen numerous issues with EFL 1.20.x Not sure what is going on... Filed several bugs today.

**Comment by Peter2121** [comment]
I think that the problem is in theme file, used by ecrire

**Comment by wltjr** [comment]
Ecrire has no theme file :) I have considered it but not sure I like edje and not sure anyone wants to theme ecrire. At best I could see doing it for maybe mobile and desktop UI. Though I would think that to apply to E in general and not be Ecrire specific. I feel ecrire will always go with the general E theme. Not sure anyone would want a theme specific for ecrire. Other things use themes for like effects, like ephoto. But similar effects can be done in code without requiring edje.

Given problems I see with edje and entrance bad code, etc. I really dislike edje and its fraught with issues. They seem to keep changing things that break many things. Why most old themes do not work with current EFL.

Anyway I opened an upstream [task on phab T6147](https://phab.enlightenment.org/T6147). I would be happy to address. But I have spent time chasing my tail on other issues to find out the problem lies else where... Like this [one with entrance and edje blowing up](https://phab.enlightenment.org/T6133). Look at that log file attached to that task, and then what I found out was the real problem. Or this [one with pinentry efl dialog positioning being off](https://phab.enlightenment.org/T5708) 2nd attempt, the 1st is referenced.

I have seen way to many bugs in both EFL and E to have much confidence sadly... Still have a few elm_code issues open... Ecrire is mostly a wrapper, and pretty minimal code thus few places for it to be off. Though I do know the search/replace issues in ecrire are me, and some other stuff. Thus some issues still open here, that do not have links to upstream issues.

**Comment by wltjr** [comment]
BTW really glad you ran into this before I made any further changes. I am planning on adding a history to the file dialog. Not sure I would have it be present for file saving, but its basically the same dialog for opening or saving. Along those lines are you having any issues on opening or just saving? Seems like it should be any use of that dialog. If its just save, that is strange.

Anyway I was thinking to add a hoversel/drop down/combobox at the top of the file dialog for recently opened/saved files. Likely the last ~10, maybe more. That likely would not cause any issues, but would be further modification which may cause issue. I will wait till we figure out this issue before proceeding on that front :)

**Comment by Peter2121** [comment]
Yes, the problem is present showing "Open" dialog as well.

**Comment by NuLogicSystems** [comment]
That's the file selector bug that was fixed not too long ago.

**Comment by wltjr** [comment]
That may explain why I did not see it in latest git. I guess its fixed, and can close upstream issue.

**Comment by Peter2121** [comment]
I confirm that the problem has gone after EFL updating.
