### ISSUE TITLE
Selection doesn't cancel if you click outside the text lines

### ISSUE THREAD

**Issue by ApostolosB** [Obsidian-StudiosInc/ecrire#23]
As the title suggests.
If you select text and click below the numbered lines the selection doesn't cancel.

Minor annoyance :/

**Comment by wltjr** [comment]
Not able to replicate, likely a regression maybe in git not in release. I am on EFL 1.20.6 and E 0.22.1. But once again likely an elm_code bug. Possibly not, but most focus and selection related issues are within elm_code or elementary.

**Comment by wltjr** [comment]
Adding upstream so they are aware of issues
@Enlightenment @ajwillia-ms @zmike

**Comment by ApostolosB** [comment]
Yep. Replicates with Test > Code Editor

**Comment by wltjr** [comment]
Ok thanks, that confirms its an EFL/elm_code issue sadly.... Please try to find an issue I can fix :) hehe I much rather blame myself for any issues and having some ability to fix. When its in EFL/elm_code I am at a loss. I guess I can see about making a wrapper to fix issues or patches that won't go upstream. How I ship them with ecrire, etc. Just nothing good there. Thanks for the report. Doing a great job finding new issues!

**Comment by andydotxyz** [comment]
This is now fixed upstream and will be in a future release. It may not be the next patch relase as it's related to the layout which changed since last major release. That should not be an issue as it was reported against git it would seem.

Not sure what you mean about patches not going upstream, we usually accept contributions...

**Comment by wltjr** [comment]
Thank you for the update. I will keep this open till the release comes out and update cmake version dependencies so the issue can be closed. Till then best to keep open in case others run into the problem.

Its hard to submit any contributions when you disable ones phab account and same for mailing list. I had to use one of my other email addresses to be on list. Those things discourage rather than encourage contributions.

**Comment by ApostolosB** [comment]
Yep. Just tested with git and its fixed.

**Comment by wltjr** [comment]
@ApostolosB can you test in EFL 1.20.7. We can close this if its resolve in that version. Thanks!

**Comment by ApostolosB** [comment]
Yep works on 1.20.7. However it revealed another issue. If you click outside the text lines and try to select it doesn't.

**Comment by wltjr** [comment]
We can leave this open, or file a new one. Can you provide exact steps to reproduce? Thank you!

**Comment by ApostolosB** [comment]
i'll file a new one.
