### ISSUE TITLE
Ecrire settings freeze the system when ecrire is run from the command line

### ISSUE THREAD

**Issue by ApostolosB** [Obsidian-StudiosInc/ecrire#26]
##### Description
Description of issue
As the title suggests. EFL app have the ability to run from the command line. The settings being a separate window causes the system to freeze. AFAIK this is the reason the settings of all efl apps are inside the app and not implemented as a separate window. 

##### Steps to reproduce
1. Type ecrire to a command line
2. Click Settings
3. Freeze

##### System information
- EFL Version
Stable
- E Version
Stable
- X or Wayland
None of the above. KMS i think 😛

**Comment by wltjr** [comment]
Odd I am not able to replicate. FYI that is how I run ecrire when I do development. Like when I switched over to the settings. It was always in pop up window. I just changed to naviframe for now since I was running out of vertical space. The one in git.e.org also has a windowed settings dialog. You can see a [screenshot here]. I also switched to the elm wrappers for like ecrire --help, and for the main function. Though I think I saw a bug recently on a sample app crashing or something. Maybe related to this [stuff](https://phab.enlightenment.org/T6262). Thanks for the report I will keep my eye out for it and see if I can replicate. Its likely some EFL bug once again... Though maybe avoidable by not using naviframe or something. Eventually likely do a settings like etui and terminology, but hopefully via code not edj. Though edj for effects and layout may happen. Definitely not for styling/theme stuff. So if someone writes a theme for E all of ecrire will change. Not just some parts that I did not theme. Need to provide a patch for etui for such. Not sure about verne but has aspects that are in its theme and do not change. Anyway for now I went with naviframe. Though not sure if that is the problem or the elm_main startup, or the command line argument wrapper... More EFL bug fun :P

**Comment by ApostolosB** [comment]
Do you by any chance have X running on another tty? Can you test with nothing else running?

**Comment by wltjr** [comment]
X is on vt7 here, which should be common the common one. What do you mean nothing else running? No other apps? Do you mean EFL starting from a terminal or something without E running or any graphics?

**Comment by ApostolosB** [comment]
I mean without X running  on another VT

**Comment by wltjr** [comment]
Are you able to start other applications like that? Like rage, or ephoto? I would need to be able to have some application I could start from command line. Not sure I have any that work short of Wayland and I cannot get that running yet. Pretty sure X cannot be started that way, short of startx or something.

**Comment by wltjr** [comment]
This should be resolved now. Please test and close if the issue is resolved, thank you!

**Comment by ApostolosB** [comment]
Fixed.  Thanks.
