### ISSUE TITLE
Kill the animation on start

### ISSUE THREAD

**Issue by ApostolosB** [Obsidian-StudiosInc/ecrire#28]
##### Description
Description of issue
Not an issue per se but i somehow find it annoying. When you open file with ecrire there is this animation of the text rising from the bottom of the window. Can we eliminate that or add a setting option to not have it. I prefer to double click and show the text file immediately. 

##### Steps to reproduce
1. Just double click on a file

##### System information
- EFL Version
Stable 
- E Version
Stable
- X or Wayland
Wayland

**Comment by wltjr** [comment]
Yes for sure, I have been meaning to add a configure option for that, enable/disable animations. Even though just the one, maybe others later.

**Comment by ApostolosB** [comment]
Cool. Thanks 😄

**Comment by wltjr** [comment]
Ok there you go. :) May add more options later, ability to control direction, speed, and maybe other types of animations. But for now a simple check box. On by default, but can turn off. If you have any crashes may need to nuke the ecrire.cfg file. Eet is crash happy at times. Otherwise if any issues please re-open or file a new issue. Thanks

**Comment by ApostolosB** [comment]
Works fine. Thanks again.
