### ISSUE TITLE
Save dialog issues

### ISSUE THREAD

**Issue by ApostolosB** [Obsidian-StudiosInc/ecrire#40]
##### Description
Description of issue
Save dialog of a new file doesn't appear in the center of the window

##### Steps to reproduce
1. Open ecrire 
2. Type something
3. Hit Save 
4. ...
5. Profit > https://www.enlightenment.org/ss/display.php?image=e-5b950df1822884.63839290.png top left

##### System information
- EFL Version = 1.21
- E Version = 0.22.4
- X or Wayland = wayland

**Comment by wltjr** [comment]
Wonder if this is wayland related. I saw the same and fixed the issue under X. See the screenshots in  issue #37. It is likely settings dialog is also off centered. Not sure why it still is present under wayland.

**Comment by ApostolosB** [comment]
Settings are centered. If you resize with settings open things don't look good.

Ie. > https://www.enlightenment.org/ss/display.php?image=e-5b953bfc855331.08438811.png

**Comment by wltjr** [comment]
That is odd about settings being centered but not the file dialog. Before settings was slightly off in my first comments on #37. I will have to look into getting settings bound to the window. Like the save, discard, cancel dialog. That is a popup vs inwin, so bit different. But that does resize when the window is resized. Nothing else does file nor settings

**Comment by wltjr** [comment]
@ApostolosB see if recent changes makes any difference. I did fix the re-sizing issue with settings. Not sure why settings is centered properly and the file dialog is not. Really curious what happens with the file dialog when you resize. Since it starts off centered. I wonder if that ever corrects with the recent changes. Likely no change with settings, other than it re-sizing when the window is resized.

I should not have to add code to handle resizing of the window for ```elm_inwin```. But seems there is some side effect from using ```efl_part```. Which I need for getting the background color, for alpha settings purposes. Anytime I call ```efl_part```, it causes issues for the inwin's. It makes them off centered, both settings and file dialogs. I had to add code to resize the inwin to the size of the window to fix the centering. That was what caused them to not re-size when the window resized. Which I added code so when the window is resized it resizes the inwin.

Despite these modifications, the file dialog may remain off centered. I am not sure why the file dialog is not centered and the settings dialog is centered. That maybe a Wayland specific issue. If no change on resize with file dialog. I will have to test under Wayland.

**Comment by wltjr** [comment]
Hopefully that last commit fixes the centering issue with the file dialog. I was settings its geometry using values from the config file rather than from the window itself. For settings I got the geometry from the window. That was the main difference between file and settings dialogs. Now it is the same for both. Which should correct the file dialog centering. Since settings was centered correctly.

If it does not fix the issue, then I will have to test under Wayland.

**Comment by ApostolosB** [comment]
Both seem to work ok unless you resize smaller (in the case of settings also larger -but that is not as ugly) than the size of them where you get:
This:
https://www.enlightenment.org/ss/display.php?image=e-5b96cf2febf050.99870154.png
And this:
https://www.enlightenment.org/ss/display.php?image=e-5b96cfa26a4bf4.85682480.png

This could be an efl bug so i'll ask the devs tomorrow.

**Comment by wltjr** [comment]
I think something is off in Wayland. It looks nothing like that in X11. What does settings look like when larger?

This is what it looks like under X11. I can make it pretty tiny and it is always within the window. Just not really usable when smaller than pictured.
![shot-2018-09-10_16-20-45](https://user-images.githubusercontent.com/12835340/45322279-ce025480-b515-11e8-966b-9bc61a8a1079.jpg)
![shot-2018-09-10_16-21-01](https://user-images.githubusercontent.com/12835340/45322290-d78bbc80-b515-11e8-9612-53edb189e300.jpg)

**Comment by ApostolosB** [comment]
Larger:
https://www.enlightenment.org/ss/display.php?image=e-5b96d879e6fbd5.09483499.png

**Comment by wltjr** [comment]
That is what it looked like for me before I made the change to resize when you change window size. Seems like that is not happening in Wayland. It should scale with the window.

**Comment by wltjr** [comment]
May want to double check you building from latest git head. If you are then my recent changes did not seem to help much. Other than making the file dialog visible again. I guess that is something, but should address the resizing issue as well.

**Comment by ApostolosB** [comment]
Yep. Git head. Build before i tested and rebuild again just to be sure.

**Comment by wltjr** [comment]
That seems to confirm there is different behavior under X11 and Wayland. Or there are other changes in EFL if your using git there as well. 1.21.1 is supposed to come out this week. It will be interesting to see what that brings. 1.21 broke entrance and had some new issues effecting ecrire. Still haven't fixed Entrance yet, really odd issue there.

I will see if I can setup a Wayland test env. One major thing keeping me off Wayland is support for Synergy or equivalent. Not sure Barrier works yet on Wayland. I have multiple machines, min desktop and latop, but at times multiple laptops. Synergy makes it feasible with 1 mouse and keyboard for all. I am able to finally run Wayland with a patch for elogind and modified pam env for startup.

Thanks for testing and confirming! Sorry the changes did not work out in Wayland. They did fix the issues in X11. Least ones I could reproduce, like the scaling up/down with window size.

**Comment by wltjr** [comment]
Just checked under Wayland, and seems a signal was not being fired. Which was used to initiate the resize of the inner dialogs/inwin. The last commits referenced should resolve the issue.

**Comment by wltjr** [comment]
That showed another problem. Ecrire under Wayland never saved its geometry, if you resized the window. Commit 16776e1 fixed that. That also relied on the "moved" signal. Which for what ever reason is not fired under Wayland. That is why settings was centered but file dialog was not. File dialog used the geometry from config file, which was never saved under Wayland.

I need to recode some of that to shared code vs duplicated for the dialogs. Either way shows that things are not the same under X11 and Wayland. Wayland has issues not present under X11. Pretty sure those signals should be called. Though seems it was "moved" not "move", but "move" works under X11. Go figure...

Either way should be good now. Resolved 
- dialog centering
- resize dialogs with window
- save window size under Wayland

Resolve this issue, and others discovered as part of this issue. Thanks!

**Comment by ApostolosB** [comment]
Behaves better now. The graphical glitches seem to be enlightenment related and i'll discuss them in the afternoon with the devs.

**Comment by wltjr** [comment]
Wayland seems to have more than X. I know when I resize a window with a file dialog. The icons seem to dance a bit. Either way sounds like we can close this issue now. Unless you are still experiencing off center dialogs and/or dialogs not resizing.

**Comment by ApostolosB** [comment]
Closing.

**Comment by wltjr** [comment]
Cool thanks! I tend to prefer the reporter close any issue as confirmation it is resolved for them. To easy to mark something as resolved for me that is not for another. Thanks!
