### ISSUE TITLE
Ecrire fails with latest git

### ISSUE THREAD

**Issue by ApostolosB** [Obsidian-StudiosInc/ecrire#45]
##### Description
Description of issue
As the title suggests. It doesn't start neither compiles.

##### Steps to reproduce
1. Try to compile
2. Try to run it

##### System information
- EFL Version > git
- E Version > git
- X or Wayland > wayland

**Comment by wltjr** [comment]
Thanks for the report! I meant to open an issue on this myself. I noticed the API function name changes during the pre-releases. I fixed the issues on Friday, but I have not pushed them out because they will fail to build here.

I need to find updated EFL packages for Ubuntu, the [niko2040/e19 ppa](https://launchpad.net/~niko2040/+archive/ubuntu/e19) has gone stale. There were never any packages for efl 1.21.x. I do not expect to see any for 1.22.0. The nick niko2040 is no longer registered on freenode. I think they are done and gone.

I may have to see about building it myself and hosting it somewhere. I had to do that for [argp-standalone](https://github.com/Obsidian-StudiosInc/travis-ci-musl-argp), but likely do it different for efl if I go that route, creating a ppa, etc like the e19 one.

**Comment by ApostolosB** [comment]
There are some .deb files here > https://sparkylinux.org/repo/pool/main/e/efl/

No idea if they'll work with ubuntu (haven't touched that in ages) or destroy your pc, every form of life or whatever.

**Comment by wltjr** [comment]
Thanks, I may give those a try, worse case it does not work. Its VMs in CIs so not concerned about any destruction.

Ideally I need to build a docker image for EFL apps. I tried to bring such up to the dev community sometime back. I really would like a image that has everything already installed, EFL, Meson, CMake, etc. Anything needed to build EFL apps. I lose a considerable amount of time in CI just installing the stuff over and over again, EFL, Meson, etc. I just haven't had the time to make up such docker images yet... But I will have to sooner rather than later, if I cannot get a working deb for Ubuntu for CIs.

**Comment by wltjr** [comment]
@ApostolosB I made a [docker-efl image](https://hub.docker.com/r/obsidianstudios/efl) last week, but I am not sure if I will switch to that or create my own PPA and deb packages for efl/Ubuntu. Eventually, I will make one for enlightenment as well.

The docker-efl has pros and cons. Ideally, it will be faster to use since packages do not need to be installed. Though, I do need to compare time to download docker image vs downloading and installing packages. However, using docker comes with a major pro and con. All the work must take place within the docker image. I must completely redo my CI setups and tests. The major pro there is it makes it fully portable and no longer bound to Travis-CI. Though the downfall/con is it could start using other CI's like Shipable more than I want. I only have Shippable doing basic testing and Travis doing other stuff like code quality and making binaries for deployment.

Still trying to decide on all that, and figure out the change necessary so I have all the same functionality I have now. In that process, I may just decide to create a PPA and go that route. Leaving everything in repos setup as is now. The main negative with that approach, beyond time to create PPA/deb, etc is that it does not help speed up CI builds. That is semi-moot, most times except for during development. The faster CI builds and tests are run, the faster things can be developed in theory.

I still like the docker aspect for having a pre-build env to build and test ELF apps. That was my initial rationale and logic. However, it is the usage, that makes that less than ideal. I basically end up redoing all the CI builds and tests, though in a more portable manner. Pros and cons, as there are with anything in life.

I have't forgot about this. I fixed it as soon as I encountered it. It is just the lack of EFL 1.22.x for CI that has me stuck... Hopefully, I will get this all squared away this week. It has been some time coming. I have been thinking about the docker stuff for a while. I tried to talk to others, but they are more interested in [building EFL](https://github.com/marcelhollerbach/efl-ready-docker), than having a docker image with EFL for application development, etc.

**Comment by wltjr** [comment]
@ApostolosB I pushed out the changes in a branch for now, feel free to grab that as a patch. I am in a CI nightmare with EFL... It seems all CI's use older versions of Ubuntu that do not satisfy EFL requirements, need newer versions of some dependencies. The latest any offer is xenial 16.04, and I need at least bionic 18.04. For some odd reason, most CI's still offer Trusty 14.04 now EOL as of April 2019, and also Precise 12.04 which is beyond [EOL](https://en.wikipedia.org/wiki/Ubuntu_version_history)... Travis default is still [trusty](https://docs.travis-ci.com/user/reference/overview/). No better with [Shippable](http://docs.shippable.com/platform/runtime/machine-image/os-versions/). CircleCI uses docker images, so that is very different. Not sure of others or if any offer newer Ubuntus.

I spent several days trying to package EFL 1.22 for [ubuntu](https://launchpad.net/~wltjr/+archive/ubuntu/epkgs) xenial or bionic. I built against bionic in [Docker](https://hub.docker.com/r/obsidianstudios/efl), but having issues in Launchpad I did not run into in Docker. It is looking like I may have to use the docker image for CI testing, as that is the only way to get a newer version of the dependencies.

Anyway for the time being please refer to patch in PR #46

**Comment by wltjr** [comment]
I may just go back and add in some conditionals on EFL versions so it works for both < 1.22.x and >= 1.22.x. Likely easier way to go at this point... Though does not solve the I need 1.22.x for testing in CI.

**Comment by wltjr** [comment]
@ApostolosB I broke down and added in conditionals... At least till I can get the EFL CI situation resolved, which is likely not of much interest. I will close this once CI builds run.

I believe I got one in, but not 100%. Github is having some issues preventing any CI's from running. Once those run and pass, I will close this issue. If building from git, may have to force pull after I force push to get Github to notify CI's. Unless that happens as part of Github's resolution of the notification issue.

**Comment by wltjr** [comment]
CI's passed, issue is resolve, closing.

**Comment by ApostolosB** [comment]
i get this > https://www.enlightenment.org/ss/display.php?image=e-5ced1e88bd37e2.97919825.jpg

tested on git.

**Comment by wltjr** [comment]
I assume you built that with Meson? Looks like something is off, the mention of ```version: unknown``` does not look correct. Seems like it installed the CMake files without a version.

**Comment by ApostolosB** [comment]
Yes. efl is build with meson.

**Comment by wltjr** [comment]
That maybe a bug in the meson build system, causing the `version: unknown`. You can see what pkg-config finds `pkg-config eo --modversion`, should return a version. May also check the `libeo.so`, and see its version, like `libeo.so.1.22.2`.

I need to work on switching my Gentoo ebuild for EFL over to Meson. Till then, I am still on autotools,  not sure the problem exists there. I need to test, but I would assume its meson related.

**Comment by ApostolosB** [comment]
I pinged marcel and he has a fix pending review. I'll test once it lands on git.

**Comment by wltjr** [comment]
Ok, thank you for doing that!

**Comment by ApostolosB** [comment]
https://www.enlightenment.org/ss/display.php?image=e-5cfe8907773af1.52301944.jpg 

one more obstacle.

**Comment by wltjr** [comment]
Strange, that seems meson related as well. I cannot replicate with autotools. Not sure there is any way for me to fix, seems like another EFL issue.
