### ISSUE TITLE
Replace is not an undoable action

### ISSUE THREAD

**Issue by ApostolosB** [Obsidian-StudiosInc/ecrire#8]
To rep:
Open a new win
Type two words (ie test test)
Hit search
In the search for field type test 
In the replace field type whatever you want (ie fail)
Click replace all
Then click undo
It will delete the last few letters.

**Comment by wltjr** [comment]
Undo/redo is handled by elm code. Not sure if I need to register something with elm code or a bug, or how I am using the API. Seems it should be aware of changes via manual entry or replace. I will look into this, thanks for the report.

**Comment by ApostolosB** [comment]
Sorry for creating noise here but i don't know whether bugs are elm_code related or ecrire related. If its something obvious efl related i usually file it on phab (ie the file selector). 

Its going to be a bumpy ride since elm_code is brand sparkling new and has its issues as it seems.

**Comment by wltjr** [comment]
I do not mind. It is hard to say offhand if this stuff is elm code, or ecrire hooks around elm code. I think most are elm code related. I am not able to use EDI much if at all without crashes. Though I know ecrire has some of its own issues and may not be using the elm code API correctly in places. Its all a work in progress. Still not many docs on elm code yet, as its still in development. Ecrire is the first to use other than EDI. Which seems is good as its potentially showing a bunch of bugs in elm code. That may not have been detected otherwise. Though i am sure some is ecrire specific. Thus this is the best place. I will filter through and report back to phab/e any elm code specific issues. Its all good! Thank you for taking your time to test and report!

**Comment by wltjr** [comment]
This should be resolved now, seems so for me at least. I am going to close this issue. Please re-open if the problem remains.
